spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buncheoleasy_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    buncheoleasy.buncheol: TRACE
    buncheoleasy.auth: TRACE
    org.springframework.security: TRACE
    org.mybatis: TRACE
    org.apache.ibatis: TRACE
    org.springframework.jdbc: TRACE

app:
  base-url: http://localhost:8080

delivery:
  tracker:
    client-id: ${DELIVERY_TRACKER_CLIENT_ID:AA51v5vLZjyCdwZYhCmguSbp}
    client-secret: ${DELIVERY_TRACKER_CLIENT_SECRET:kEZaK7wH3XbZkN9vPr4jauO1qMCCNYUz8juRuBAN4EJ}
    callback-url: http://localhost:8080/v1/deliveries/webhook/callback
